reddit:
  baseUrl: https://old.reddit.com

lemmy:
  baseUrl: https://lemmy.dbzer0.com

communityMap:
  - subreddit: incremental_games
    postFilter:
      postLimit: 50
      minUpvotes: 10
      maxDownvotes: 1000
      minUpvoteRatio: 0.75
      maxTimeHours: 48
      excludedUrlPatterns:
        - v\.redd.it\/\w+
        - reddit\.com\/.*\/what_games_are_you_playing
        - reddit\.com\/.*\/help_finding_games_and
    community:
      name: incremental_games@incremental.social
      postIfQuietFor: 24
